name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: oprypin/find-latest-tag@v1
        with:
          repository: merkio/gym-app  # The repository to scan.
          sort-tags: true
          releases-only: true  # We know that all relevant tags have a GitHub release for them.
        id: octokit  # The step ID to refer to later.

      - run: echo "Octokit is at version ${{ steps.octokit.outputs.tag }}"
      - uses: actions/checkout@v2
        with:
          repository: merkio/gym-app
          ref: ${{ steps.octokit.outputs.tag }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - uses: actions-ecosystem/action-get-latest-tag@v1
        id: get-latest-tag
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            geekspace/gym-app:latest
            geekspace/gym-app:${{ steps.get-latest-tag.outputs.tag }}
